### ISSUE TITLE
live cert site re-directs to bad page and triggers 500 error

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#200] opened 2021-06-15 13:55 UTC
Currently there are two different versions of the certification site accessible:

Original:
certification.ubuntu.com

New:
www.ubuntu.com/certified

People with certification.ubuntu.com bookmarked are going there, attempting to search for specific vendors, and ending up with broken links and web errors.

To reproduce:

1. go to https://certification.ubuntu.com/server/
2. In the search bar enter a string like "Supermicro"
3. hit Return/Enter
4. End up at a 500 Internal Server Error page

The URL crafted looks like this when you use the search:
https://ubuntu.com/certified/server/models?query=supermicro

I've received several complaints about this now from different people, both internally and externally.

Seems like a quick fix, just make any connection to certification.ubuntu.com redirect to https://ubuntu.com/certified instead.

Alternately, it may be good to have it redirect to a placeholder page first that says something like "https://certification.ubuntu.com is being sunset. In XX seconds you will be redirected to the new Ubuntu Certified Hardware website <HERE (Link)>."

**Comment by codersquid** [comment] 2021-06-15 14:01
This is a duplicate of https://github.com/canonical-web-and-design/ubuntu.com/issues/9901 and Carlos has a MR for it.

**Comment by carkod** [comment] 2021-06-16 08:52
Duplicated as Sheila said, and fixed already.

**Comment by nottrobin** [comment] 2021-06-16 08:52
Everything mentioned here seems to work now, is that right @bladernr ? Do you consider this fixed?

**Closed as completed by carkod** 2021-06-16 08:52 UTC
Labels: Priority: High
